Rename scripts

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -7,3 +7,9 @@ if [ $? -ne 0 ]; then
 fi
 
 coverage report
+
+pyright $@
+if [ $? -ne 0 ]; then
+    echo "Typecheck failed"
+    exit 1
+fi
